version: "3.1"


services:
  jupyter:
    build:
      context: .
      dockerfile: compose/celery/Dockerfile
    container_name: notebook
    env_file:
      - ./envs/db_keys
    ports:
      - "8888:8888"
    volumes:
      - ./src:/src
    command : ["sh", "-c", "jupyter notebook --allow-root --ip 0.0.0.0 --port 8888"]

  db:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - ./envs/db_keys
    volumes:
      - /psql_db/postgres_data:/var/lib/postgresql/data
      - /psql_db/postgres_data_backups:/backups

  adminer:
    image: adminer
    restart: always
    container_name: admin
    ports:
      - "8080:8080"

  redis:
    image: redis:3.2-alpine
    container_name: redis
    volumes:
      - ./redis_data:/data
